### ISSUE TITLE
Feature request: input ports on display widgets

### ISSUE THREAD

**Issue by trondarild** [ikaros-project/ikaros-3#20]
It would increase usage flow when building models if display widgets like plot and grid were equipped with an input port. It should still be possible to manually type in input to the widget for use in displays that do not feature a compute graph.

**Comment by ikaros-project** [comment]
This is planned. Or some alternative feature with similar functionality.

**Comment by ikaros-project** [comment]
It is now possible to drag from an output to a widget to set the source parameter of that widget.
