### ISSUE TITLE
Delete button is not working

### ISSUE THREAD

**Issue by ikaros-project** [ikaros-project/ikaros-3#30]

**Comment by ikaros-project** [comment]
Delete works for connections only now.

**Comment by ikaros-project** [comment]
Delete now works for all component types.

**Comment by trondarild** [comment]
When adding then trying to delete a module get error message that it can't be deleted.

**Comment by ikaros-project** [comment]
Do you have the latest version of the brainstudio.js? This message has been removed from the code. What is the exact wording of the error message?

**Comment by trondarild** [comment]
Sorry, only had to reload, works now!
