### ISSUE TITLE
input.connected() function slows down communication with WebUI

### ISSUE THREAD

**Issue by pierreklintefors** [ikaros-project/ikaros-3#33]
Using if statements with multiple calls of the connected() function slowed down the updates with WebUI significantly. Using if(!input.empty()) does not slow it down.

**Comment by ikaros-project** [comment]
This is very strange. Here is the definition of connected:

        const bool connected()
        {
            return !empty();
        }

It should not be notably slower than calling empty directly.  Something else must be going on.

**Comment by ikaros-project** [comment]
Reopen if needed!
