### ISSUE TITLE
Feature request: Connections with Bezier curves

### ISSUE THREAD

**Issue by trondarild** [ikaros-project/ikaros-3#47]
For ultimate beautiful graphs, nothing beats Bezier curves!

**Comment by ikaros-project** [comment]
Good idea. It should be combined with some form of automatic routing and control points that can be manually edited. Probably not too hard to add.

**Comment by ikaros-project** [comment]
We should look at various drawing programs to find an easy way to edit curves before doing this. There are interesting questions about what happens to the curves when a module is moved.
