### ISSUE TITLE
Feature request: quit after x ticks

### ISSUE THREAD

**Issue by trondarild** [ikaros-project/ikaros-3#48]
When running from command line with parameters not only want ikaros to stop after a number of ticks, but actually quit so a new instance can be started and run and output can be collected. Hence either need to quit instead of stopping, or have a -q[numticks] option. 

Alternative would be to supply a file of parameter values so the model will be restarted and run automatically with new parameters for each line in that file.

**Comment by ikaros-project** [comment]
Good point. The questions is whether we ever want the execution to stop but not quit when started from the command line. The stop option will be changed to quit for now.
