### ISSUE TITLE
Feature request: reshape matrix in connections

### ISSUE THREAD

**Issue by trondarild** [ikaros-project/ikaros-3#50]
Reminder to implement matrix reshape in connections.

**Comment by ikaros-project** [comment]
Do you mean reshape or resize?

Reshape (=putting new indices on the data) is available using different index ranges for source and target, but examples are missing.

Resizing is also mostly implemented but there is no interface (or examples) for it yet.

**Comment by trondarild** [comment]
Ok, I meant reshape, but I guess also available in the webui!

**Comment by ikaros-project** [comment]
There is now a field in the inspector for connections to add ranges in brackets. There is currently no error detection so anything can happen if the syntax is not correct.
