### ISSUE TITLE
Fix audio choppiness

### ISSUE THREAD

**Issue by trondarild** [ikaros-project/ikaros-3#53]
The function generator and the audiooutput modules need to use the internal timing functions to ensure smooth output

**Comment by ikaros-project** [comment]
This is planned for function generators and oscillators by using rate parameters everywhere.

It would be great with an audio output module that could use a matrix as an audio buffer that is filled and converted to audio at each tick.

**Comment by ikaros-project** [comment]
The new module Oscillator is supposed to replace FunctionGenerator. It will use real time instead of ticks but is not ready yet.

**Comment by trondarild** [comment]
Ok sounds good! OutputAudio checked in that exactly takes a matrix buffer and converts to audio, but it's a little choppy still due to rate issues. I guess we can remove FunctionGenerator when oscillator is ready, I just checked it in for testing the audio module.

**Comment by ikaros-project** [comment]
The new scheduler will include a priority setting for modules that will increase temporal stability it may still be necessary to hand over the sound buffer to a separate thread with more exact timing if it is not already available as af function in the AudioToolbox. A small delay would limit choppiness.

**Comment by ikaros-project** [comment]
Would it be useful to generate sound buffers from the oscillator module? This would allow the oscillator module to generate signals with frequencies that are higher than 1/ tick_duration. Not sue what the use case would be though, except for sound synthesis.

**Comment by ikaros-project** [comment]
Choppiness is probably fixed with some mutexes and double buffering
