### ISSUE TITLE
Module info is not updated if parameter added

### ISSUE THREAD

**Issue by trondarild** [ikaros-project/ikaros-3#6]
After adding a (option) parameter to cc and ikc file, the new parameter is not shown in the info window in an already saved ikg file made prior to adding the new parameter.

**Comment by ikaros-project** [comment]
The class part of the module is probably not replaced when creating the module.

**Comment by ikaros-project** [comment]
This may require version handling.

It probably works if run from the command line, but not from the WebUI.

**Comment by ikaros-project** [comment]
Deep merge is needed for dictionaries to handle this.
